require("./css/histoires.css");
//TODO mettre dans boot.js
Time = {};
require ("./js/boot.js");
require ("./js/ga.js");
require ("./js/histoires.js");
require ("./js/historic.js");
require ("./js/viewport.js");
require ("./js/barFactory.js");
//require ("./js/bar.js");
//require ("./js/barDrawer.js");
//require ("./js/barLoading.js");
require ("./js/phrasesDrawer.js");
require ("./js/scale.js");
require ("./js/data.js");
//require ("./js/data.mock.js");
require ("./js/filter.js");
require ("./js/phrases.js");
require ("./js/tooltips.js");
require ("./js/sources.js");